import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import SearchForm from "../components/SearchForm";
import search from "../helpers/search";


const Home: NextPage = () => {

  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <SearchForm search={search} />

      <Footer />
    </div>
  );
};

export default Home;
