import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import SearchForm from '../components/SearchForm'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Google | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Body */}
      <SearchForm />

      {/* Footer */}
    </div>
  )
}

export default Home
